/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Example: typeof import('./src/components/data/datatable/Example.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UiBlock: typeof import('./src/components/layout/UiBlock.vue')['default']
    UiButton: typeof import('./src/components/button/UiButton.vue')['default']
    UiCol: typeof import('./src/components/layout/UiCol.vue')['default']
    UiDataTable: typeof import('./src/components/data/datatable/UiDataTable.vue')['default']
    UiDataTableColumn: typeof import('./src/components/data/datatable/UiDataTableColumn.vue')['default']
    UiDataTableInstance: typeof import('./src/components/data/datatable/UiDataTableInstance.vue')['default']
    UiDemo: typeof import('./src/components/data/datatable/UiDemo.vue')['default']
    UiFlex: typeof import('./src/components/layout/UiFlex.vue')['default']
    UiForm: typeof import('./src/components/form/UiForm.vue')['default']
    UiGrid: typeof import('./src/components/layout/UiGrid.vue')['default']
    UiInputText: typeof import('./src/components/form/UiInputText.vue')['default']
    UiSubmitButton: typeof import('./src/components/form/UiSubmitButton.vue')['default']
    UiTextField: typeof import('./src/components/form/UiTextField.vue')['default']
    UiToolbar: typeof import('./src/components/panel/UiToolbar.vue')['default']
  }
}
